version: '5'

volumes:
  data:

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data